# Proxmox installation specific
STORAGE_POOL: "local-lvm"

# Region & Timezone
TIMEZONE: "Europe/Budapest"

# Target distro: suse, ubuntu
DISTRIBUTION: "suse"

# Template VM details
VM_VMID: "9001"
VM_NAME: "template-{{ DISTRIBUTION }}-{{ VERSION }}"
VM_MACHINE: q35
VM_CPU: host
VM_CORES: 2
VM_DISPLAY: vmware
VM_MEMORY: 1024
VM_ROOT_SIZE: "10G"
VM_BRIDGE: "vmbr0"

# Pre-install packages
PACKAGES:
  - qemu-guest-agent
  - sudo
  - traceroute
  - nano